name: Build Windows

on:
  push:
    branches: ["main", "unstable"]
  pull_request:
    branches: ["main", "unstable"]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Get dependencies
        run: |
          go get -u github.com/quic-go/quic-go
          go mod tidy

      - name: Debug Directory
        run: |
          Get-ChildItem -Recurse .\cmd\ssv-dkg

      - name: Build project
        run: |
          $env:CGO_ENABLED=1
          $env:GOOS="windows"
          $env:GOARCH="amd64"
          go build -o ./bin/ssv-dkg-windows.exe .\cmd\ssv-dkg
        shell: pwsh

      - name: List all files in directory
        run: |
          Get-ChildItem -Force
          Get-ChildItem -Force bin

      - name: Run
        run: |
          .\bin\ssv-dkg-windows.exe version
          New-Item -ItemType Directory -Force -Path initiator_logs
        shell: pwsh
