# This builds the Windows version of the project. It uses the same Go version as the Linux build, but it uses a different runner and different steps

name: Build Windows

on:
  push:
    branches: ["main", "unstable"]
  pull_request:
    branches: ["main", "unstable"]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Get dependencies
        run: |
          go get -u github.com/quic-go/quic-go
          go mod tidy

      - name: Build project
        run: |
          $env:CGO_ENABLED=1
          $env:GOOS="windows"
          $env:GOARCH="amd64"
          go build -o $env:BINARY_NAME.exe -ldflags "-X main.Version=v2.1.0" ./cmd/ssv-dkg/ssv-dkg.go
        shell: pwsh
