name: Build Windows

on:
  push:
    branches: ["main", "unstable"]
  pull_request:
    branches: ["main", "unstable"]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Get dependencies
        run: |
          go get -u github.com/quic-go/quic-go
          go mod tidy

      - name: Debug Directory
        run: |
          Get-ChildItem -Recurse .\cmd\ssv-dkg

      - name: Build project
        run: |
          $env:CGO_ENABLED=1
          $env:GOOS="windows"
          $env:GOARCH="amd64"
          go build -o ./bin/ssv-dkg-windows.exe .\cmd\ssv-dkg
        shell: pwsh

      - name: List all files in directory
        run: |
          Get-ChildItem -Force
          Get-ChildItem -Force bin

      - name: Run
        run: |
          .\bin\ssv-dkg-windows.exe version
          New-Item -ItemType Directory -Force -Path initiator_logs
          .\bin\ssv-dkg-windows.exe init --validators 10 --operatorIDs 11,21,24,29 --operatorsInfoPath .\config\operators-holesky.json --owner 0x81592c3de184a3e2c0dcb5a261bc107bfa91f494 --nonce 4 --withdrawAddress 0xa1a66cc5d309f19fb2fda2b7601b223053d0f7f4 --network "holesky" --outputPath .\output --logLevel info --logFormat json --logLevelFormat capitalColor --logFilePath .\initiator_logs\debug.log
        shell: pwsh
